### ISSUE TITLE
Child process fatal error handling

### ISSUE THREAD

**Issue by Sei4or** [Danktronics/Influo#18]
Currently, if a child process encounters a fatal error, Influo will consider the work finished and move on. Influo should restart the process if the child process does not exit with a success exit code AND the configuration has `auto_restart` set to true (new configuration field).

**Comment by sithsiri** [comment]
The user should be able to choose which error codes to restart on or not restart on, maybe using a syntax like ```auto_restart: {“not”: [0]};``` or ```auto_restart: {“only”: [209, 404]};``` and still having it parse `auto_restart: true;` as well

**Comment by Sei4or** [comment]
Interesting idea. Will be fun messing with multiple types.
